### ISSUE TITLE
Which theme to install?

### ISSUE THREAD

**Issue by maxxcrawford** [paradoxxxzero/atom-one-theme-color-by-project#1]
Can you link directly to the theme that this plug-in works with? 

Example: [https://atom.io/themes/atom-dark-ui](https://atom.io/themes/atom-dark-ui)

**Comment by paradoxxxzero** [comment]
Sure:
* https://atom.io/themes/one-dark-ui
* https://atom.io/themes/one-light-ui

**Comment by paradoxxxzero** [comment]
I updated the readme.
